version: '3.7'
services:
  postgres-passport:
    container_name: passport-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: passport
  passport:
    container_name: passport
    image: passport
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://passport-postgres:5432/passport
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSOWRD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  flyway:
    image: boxfuse/flyway:latest-alpine
    command: -url=jdbc:postgresql://passport-postgres:5432/passport -schemas=schemaName -user=postgres -password=password migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    build:
      context: ./
      dockerfile: Dockerfile
